<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite245765ffc3b867cb9f23bb8ecf4986e
{
    public static $classMap = array (
        'ComposerAutoloaderInite245765ffc3b867cb9f23bb8ecf4986e' => __DIR__ . '/../..' . '/src/composer/autoload_real.php',
        'Composer\\Autoload\\ClassLoader' => __DIR__ . '/../..' . '/src/composer/ClassLoader.php',
        'Composer\\Autoload\\ComposerStaticInite245765ffc3b867cb9f23bb8ecf4986e' => __DIR__ . '/../..' . '/src/composer/autoload_static.php',
        'Eighth' => __DIR__ . '/../..' . '/src/Eighth.php',
        'Fifth' => __DIR__ . '/../..' . '/src/Fifth.php',
        'First' => __DIR__ . '/../..' . '/src/First.php',
        'FortyEighth' => __DIR__ . '/../..' . '/src/48th.php',
        'Fourth' => __DIR__ . '/../..' . '/src/Fourth.php',
        'Ninth' => __DIR__ . '/../..' . '/src/Ninth.php',
        'Second' => __DIR__ . '/../..' . '/src/Second.php',
        'Seventh' => __DIR__ . '/../..' . '/src/Seventh.php',
        'Sixteenth' => __DIR__ . '/../..' . '/src/Sixteenth.php',
        'Sixth' => __DIR__ . '/../..' . '/src/Sixth.php',
        'Tenth' => __DIR__ . '/../..' . '/src/Tenth.php',
        'Third' => __DIR__ . '/../..' . '/src/Third.php',
        'Twentieth' => __DIR__ . '/../..' . '/src/20th.php',
        'TwentyFifth' => __DIR__ . '/../..' . '/src/25th.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInite245765ffc3b867cb9f23bb8ecf4986e::$classMap;

        }, null, ClassLoader::class);
    }
}
