<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ComposerAutoloaderInite245765ffc3b867cb9f23bb8ecf4986e' => $baseDir . '/src/composer/autoload_real.php',
    'Composer\\Autoload\\ClassLoader' => $baseDir . '/src/composer/ClassLoader.php',
    'Composer\\Autoload\\ComposerStaticInite245765ffc3b867cb9f23bb8ecf4986e' => $baseDir . '/src/composer/autoload_static.php',
    'Eighth' => $baseDir . '/src/Eighth.php',
    'Fifth' => $baseDir . '/src/Fifth.php',
    'First' => $baseDir . '/src/First.php',
    'FortyEighth' => $baseDir . '/src/48th.php',
    'Fourth' => $baseDir . '/src/Fourth.php',
    'Ninth' => $baseDir . '/src/Ninth.php',
    'Second' => $baseDir . '/src/Second.php',
    'Seventh' => $baseDir . '/src/Seventh.php',
    'Sixteenth' => $baseDir . '/src/Sixteenth.php',
    'Sixth' => $baseDir . '/src/Sixth.php',
    'Tenth' => $baseDir . '/src/Tenth.php',
    'Third' => $baseDir . '/src/Third.php',
    'Twentieth' => $baseDir . '/src/20th.php',
    'TwentyFifth' => $baseDir . '/src/25th.php',
);
